server:
  port: 80
spring:
  redis:
    cache:
#      nodes: -192.168.159.129:7001
#        -192.168.159.129:7002
#        -192.168.159.129:7003
      host: localhost:6379
      password: 123456
      maxIdle: 10
      minIdle: 1
      maxTotal:
      timeout: 0
      maxWaitMillis: 5000