server:
#  port: 80
  port: 443

spring:
  data:
    redis:
      host: localhost
      port: 6379
      password: 123456

---
server:
  ssl:
    enabled: true
    key-store: classpath:/ssl/myssl.keystore
    key-store-password: 123456
    key-store-type: pkcs12
    key-alias: myssl