spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.56.101:3306/shiro?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml

shiro:
  jwt:
    secret: KsAAABUXYzDFGKwCS
    expire: 86400  # 1天

#shiro-redis:
#  redis-manager:
#    host: 127.0.0.1:6379
#    database: 10
---
spring:
  redis:
    host: localhost
    database: 1
    port: 6379
    timeout: 0
    jedis:
      pool:
        max-idle: 8
        min-idle: 0
        max-active: 8
        max-wait: -1
