# jdbc_config   datasource
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jpa?serverTimezone=UTC&useSSL=false
    username: root
    password: root

  freemarker:
    suffix: .html  #后缀名
    content-type: text/html
    enabled: true
    cache: false #缓存配置
    charset: UTF-8 #编码格式
    settings:
      number_format: '0.##'
  mvc:
    static-path-pattern: /**
server:
  port: 8088
  servlet:
    context-path: /acid

---
# auto create table
spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        hbm2ddl:
          auto: update
          format_sql: true
        # 显示原始代码
        #use_sql_comments: true

---
# Hikari will use the above plus the following to setup connection pooling
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 10
      maximum-pool-size: 25
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1