# spring:
#   ai:
#     openai:
#       base-url: https://api.deepseek.com  # DeepSeek\u7684OpenAI\u5F0F\u7AEF\u70B9
#       api-key: sk-xxxxxxxxx
#       chat.options:
#         model: deepseek-chat  # \u6307\u5B9ADeepSeek\u7684\u6A21\u578B\u540D\u79F0

spring:
  ai:
    openai:
      base-url: https://dashscope.aliyuncs.com/compatible-mode  # \u901A\u4E49\u5343\u95EE
      api-key: sk-xxxxxxxxx
      chat.options:
        model: qwen-plus