spring:
  kafka:
    bootstrap-servers: 10.113.74.45:9092,10.113.74.45:2181
#    bootstrap-servers: loaclhost:9092,localhost:2181
    producer:
      retries: 0
      batch-size: 10240
      buffer-memory: 33554432
      properties:
        linger.ms: 1000
        request.timeout.ms: 2000
        max.in.flight.requests.per.connection: 10
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: 1